language: python

matrix:
    include:
        - python: 3.5
        - python: 3.6
    exclude:
        - python: 2.7
        - python: 2.6

install:
   - pip install nose
   - pip install coverage

before_script:
   - mkdir -p shippable/testresults/
   - mkdir -p shippable/codecoverage/

script:
    - nosetests tests --with-xunit --xunit-file=shippable/testresults/nosetests.xml
    - coverage run --branch tests
    - coverage xml -o shippable/codecoverage/coverage.xml tests
